name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-api-changes:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          make build-ui
