name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-ui:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Install Yarn
        shell: bash
        run: |
          ./.github/scripts/install-yarn.sh
      - name: Build
        run: |
          make build-ui

# test
